services:
  zoo1:
    image: zookeeper:3.4.9
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ${PROJECT_PATH}/zoo/1/data:/data
      - ${PROJECT_PATH}/zoo/1/datalog:/datalog

  zoo2:
    image: zookeeper:3.4.9
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ${PROJECT_PATH}/zoo/2/data:/data
      - ${PROJECT_PATH}/zoo/2/datalog:/datalog

  zoo3:
    image: zookeeper:3.4.9
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
        - ${PROJECT_PATH}/zoo/3/data:/data
        - ${PROJECT_PATH}/zoo/3/datalog:/datalog

